name: hiperhealth
channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.10,<=3.13
  - pip
  - nodejs # used by semantic-release
  - tesseract
  - libmagic
  - uv
  - compilers # conda-forge meta-package: selects the right C/C++ toolchain per platform
  - pip:
      - paginate==0.5.6 # distlib issue
